# configs/default.yaml
# Data loading parameters
data:
  root_dir: "data/dfc25_track2_trainval"
  blacklist_path: "data/image_labels.txt"
  crop_size: 256
  num_workers: 4

# Patch extraction parameters
roi_patch_size: 16              # Size of the actual region of interest
context_patch_size: 256        # Size of the context window
patch_stride: 8              # Stride for patch extraction
pos_threshold: 0.05           # Maximum damage ratio for positive pairs
min_valid_pixels: 0.8         # Minimum ratio of valid pixels needed
positive_ratio: 0.5           # Target ratio of positive samples
max_pairs_per_image: 500      # Maximum number of pairs to extract per image - ONLY FOR SMALL PATCH VERSION

# Model parameters
model:
  optical_channels: 3         # RGB for optical images
  sar_channels: 1
  projection_dim: 128         # Dimension of contrastive projection space
  resnet_version: 18
  freeze_resnet: False         # Freeze ResNet backbone

# Training parameters
training:
  batch_size: 64
  learning_rate: 0.0001
  weight_decay: 0.0001
  num_epochs: 10
  temperature: 0.07           # Temperature for InfoNCE loss
  output_dir: "output/patch_contrastive"
  loading_checkpoint: False   # Retrain from a previous checkpoint

# Warmup parameters
warmup:
  warmup_epochs: 2
